### post new deivce
POST http://{{host}}/devices
Content-Type: application/json
X-Source: test.http

{
  "serialNumber": "d-1-sn",
  "deviceType": "light",
  "status": "active"
}

### get device info
GET http://{{host}}/devices/66eb2ddd4b72c4f70a0955a4
Content-Type: application/json
X-Source: test.http
