openapi: 3.0.0
info:
  title: API управления устройствами
  version: 1.0.0
paths:
  /devices/{device_id}:
    get:
      summary: Получение информации об устройстве
      description: Возвращает подробную информацию о конкретном устройстве по его ID.
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  device_id:
                    type: string
                  name:
                    type: string
                  status:
                    type: string

  /devices/{device_id}/status:
    put:
      summary: Обновление состояния устройства
      description: Позволяет изменить состояние устройства (например, включить/выключить).
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /devices/{device_id}/commands:
    post:
      summary: Отправка команды устройству
      description: Отправляет команду устройству (например, «установить температуру 22 градуса»).
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                value:
                  type: string
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string