// Code generated by ogen, DO NOT EDIT.
package api

type DevicesDeviceIDCommandsPostRes interface {
	devicesDeviceIDCommandsPostRes()
}

type DevicesDeviceIDGetRes interface {
	devicesDeviceIDGetRes()
}

type DevicesDeviceIDStatusPutRes interface {
	devicesDeviceIDStatusPutRes()
}

type DevicesPostRes interface {
	devicesPostRes()
}
