// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/url"
	"strings"
	"time"

	"github.com/go-faster/errors"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"
	"go.opentelemetry.io/otel/trace"

	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// DevicesDeviceIDCommandsPost invokes POST /devices/{device_id}/commands operation.
	//
	// Отправляет команду устройству (например, «установить
	// температуру 22 градуса»).
	//
	// POST /devices/{device_id}/commands
	DevicesDeviceIDCommandsPost(ctx context.Context, request *DevicesDeviceIDCommandsPostReq, params DevicesDeviceIDCommandsPostParams) (*DevicesDeviceIDCommandsPostOK, error)
	// DevicesDeviceIDGet invokes GET /devices/{device_id} operation.
	//
	// Возвращает подробную информацию о конкретном
	// устройстве по его ID.
	//
	// GET /devices/{device_id}
	DevicesDeviceIDGet(ctx context.Context, params DevicesDeviceIDGetParams) (*DevicesDeviceIDGetOK, error)
	// DevicesDeviceIDStatusPut invokes PUT /devices/{device_id}/status operation.
	//
	// Позволяет изменить состояние устройства (например,
	// включить/выключить).
	//
	// PUT /devices/{device_id}/status
	DevicesDeviceIDStatusPut(ctx context.Context, request *DevicesDeviceIDStatusPutReq, params DevicesDeviceIDStatusPutParams) (*DevicesDeviceIDStatusPutOK, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

var _ Handler = struct {
	*Client
}{}

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// DevicesDeviceIDCommandsPost invokes POST /devices/{device_id}/commands operation.
//
// Отправляет команду устройству (например, «установить
// температуру 22 градуса»).
//
// POST /devices/{device_id}/commands
func (c *Client) DevicesDeviceIDCommandsPost(ctx context.Context, request *DevicesDeviceIDCommandsPostReq, params DevicesDeviceIDCommandsPostParams) (*DevicesDeviceIDCommandsPostOK, error) {
	res, err := c.sendDevicesDeviceIDCommandsPost(ctx, request, params)
	return res, err
}

func (c *Client) sendDevicesDeviceIDCommandsPost(ctx context.Context, request *DevicesDeviceIDCommandsPostReq, params DevicesDeviceIDCommandsPostParams) (res *DevicesDeviceIDCommandsPostOK, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.HTTPRouteKey.String("/devices/{device_id}/commands"),
	}

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(float64(elapsedDuration)/float64(time.Millisecond)), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, "DevicesDeviceIDCommandsPost",
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/devices/"
	{
		// Encode "device_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "device_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.DeviceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/commands"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeDevicesDeviceIDCommandsPostRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeDevicesDeviceIDCommandsPostResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DevicesDeviceIDGet invokes GET /devices/{device_id} operation.
//
// Возвращает подробную информацию о конкретном
// устройстве по его ID.
//
// GET /devices/{device_id}
func (c *Client) DevicesDeviceIDGet(ctx context.Context, params DevicesDeviceIDGetParams) (*DevicesDeviceIDGetOK, error) {
	res, err := c.sendDevicesDeviceIDGet(ctx, params)
	return res, err
}

func (c *Client) sendDevicesDeviceIDGet(ctx context.Context, params DevicesDeviceIDGetParams) (res *DevicesDeviceIDGetOK, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.HTTPRouteKey.String("/devices/{device_id}"),
	}

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(float64(elapsedDuration)/float64(time.Millisecond)), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, "DevicesDeviceIDGet",
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/devices/"
	{
		// Encode "device_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "device_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.DeviceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeDevicesDeviceIDGetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DevicesDeviceIDStatusPut invokes PUT /devices/{device_id}/status operation.
//
// Позволяет изменить состояние устройства (например,
// включить/выключить).
//
// PUT /devices/{device_id}/status
func (c *Client) DevicesDeviceIDStatusPut(ctx context.Context, request *DevicesDeviceIDStatusPutReq, params DevicesDeviceIDStatusPutParams) (*DevicesDeviceIDStatusPutOK, error) {
	res, err := c.sendDevicesDeviceIDStatusPut(ctx, request, params)
	return res, err
}

func (c *Client) sendDevicesDeviceIDStatusPut(ctx context.Context, request *DevicesDeviceIDStatusPutReq, params DevicesDeviceIDStatusPutParams) (res *DevicesDeviceIDStatusPutOK, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("PUT"),
		semconv.HTTPRouteKey.String("/devices/{device_id}/status"),
	}

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(float64(elapsedDuration)/float64(time.Millisecond)), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, "DevicesDeviceIDStatusPut",
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/devices/"
	{
		// Encode "device_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "device_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.DeviceID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/status"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeDevicesDeviceIDStatusPutRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	stage = "DecodeResponse"
	result, err := decodeDevicesDeviceIDStatusPutResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
