// Code generated by ogen, DO NOT EDIT.

package api

type DevicesDeviceIDCommandsPostOK struct {
	Result OptString `json:"result"`
}

// GetResult returns the value of Result.
func (s *DevicesDeviceIDCommandsPostOK) GetResult() OptString {
	return s.Result
}

// SetResult sets the value of Result.
func (s *DevicesDeviceIDCommandsPostOK) SetResult(val OptString) {
	s.Result = val
}

type DevicesDeviceIDCommandsPostReq struct {
	Command OptString `json:"command"`
	Value   OptString `json:"value"`
}

// GetCommand returns the value of Command.
func (s *DevicesDeviceIDCommandsPostReq) GetCommand() OptString {
	return s.Command
}

// GetValue returns the value of Value.
func (s *DevicesDeviceIDCommandsPostReq) GetValue() OptString {
	return s.Value
}

// SetCommand sets the value of Command.
func (s *DevicesDeviceIDCommandsPostReq) SetCommand(val OptString) {
	s.Command = val
}

// SetValue sets the value of Value.
func (s *DevicesDeviceIDCommandsPostReq) SetValue(val OptString) {
	s.Value = val
}

type DevicesDeviceIDGetOK struct {
	DeviceID OptString `json:"device_id"`
	Name     OptString `json:"name"`
	Status   OptString `json:"status"`
}

// GetDeviceID returns the value of DeviceID.
func (s *DevicesDeviceIDGetOK) GetDeviceID() OptString {
	return s.DeviceID
}

// GetName returns the value of Name.
func (s *DevicesDeviceIDGetOK) GetName() OptString {
	return s.Name
}

// GetStatus returns the value of Status.
func (s *DevicesDeviceIDGetOK) GetStatus() OptString {
	return s.Status
}

// SetDeviceID sets the value of DeviceID.
func (s *DevicesDeviceIDGetOK) SetDeviceID(val OptString) {
	s.DeviceID = val
}

// SetName sets the value of Name.
func (s *DevicesDeviceIDGetOK) SetName(val OptString) {
	s.Name = val
}

// SetStatus sets the value of Status.
func (s *DevicesDeviceIDGetOK) SetStatus(val OptString) {
	s.Status = val
}

type DevicesDeviceIDStatusPutOK struct {
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *DevicesDeviceIDStatusPutOK) GetStatus() OptString {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *DevicesDeviceIDStatusPutOK) SetStatus(val OptString) {
	s.Status = val
}

type DevicesDeviceIDStatusPutReq struct {
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *DevicesDeviceIDStatusPutReq) GetStatus() OptString {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *DevicesDeviceIDStatusPutReq) SetStatus(val OptString) {
	s.Status = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
