// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DevicesDeviceIDCommandsPost implements POST /devices/{device_id}/commands operation.
//
// Отправляет команду устройству (например, «установить
// температуру 22 градуса»).
//
// POST /devices/{device_id}/commands
func (UnimplementedHandler) DevicesDeviceIDCommandsPost(ctx context.Context, req *DevicesDeviceIDCommandsPostReq, params DevicesDeviceIDCommandsPostParams) (r *DevicesDeviceIDCommandsPostOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DevicesDeviceIDGet implements GET /devices/{device_id} operation.
//
// Возвращает подробную информацию о конкретном
// устройстве по его ID.
//
// GET /devices/{device_id}
func (UnimplementedHandler) DevicesDeviceIDGet(ctx context.Context, params DevicesDeviceIDGetParams) (r *DevicesDeviceIDGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DevicesDeviceIDStatusPut implements PUT /devices/{device_id}/status operation.
//
// Позволяет изменить состояние устройства (например,
// включить/выключить).
//
// PUT /devices/{device_id}/status
func (UnimplementedHandler) DevicesDeviceIDStatusPut(ctx context.Context, req *DevicesDeviceIDStatusPutReq, params DevicesDeviceIDStatusPutParams) (r *DevicesDeviceIDStatusPutOK, _ error) {
	return r, ht.ErrNotImplemented
}
